export const province = {
  Allemagne: {
    required: false,
    name: "Région / Département (facultatif)",
    options: [
      { key: "Bade-Wurtemberg", value: "DE-BW" },
      { key: "Bavière", value: "DE-BY" },
      { key: "Berlin", value: "DE-BE" },
      { key: "Brandebourg", value: "DE-BB" },
      { key: "Brême", value: "DE-HB" },
      { key: "Hambourg", value: "DE-HH" },
      { key: "Hesse", value: "DE-HE" },
      { key: "Mecklembourg-Poméranie-Occidentale", value: "DE-MV" },
      { key: "Basse-Saxe", value: "DE-NI" },
      { key: "Rhénanie du Nord-Westphalie", value: "DE-NW" },
      { key: "Rhénanie-Palatinat", value: "DE-RP" },
      { key: "Sarre", value: "DE-SL" },
      { key: "Saxe", value: "DE-SN" },
      { key: "Saxe-Anhalt", value: "DE-ST" },
      { key: "Schleswig-Holstein", value: "DE-SH" },
      { key: "Thuringe", value: "DE-TH" },
    ],
  },
  "Espagne (hors Baléares, Canaries, Ceuta, Melilla)": {
    required: true,
    name: "Province",
    options: [
      { key: "A Coruña", value: "C" },
      { key: "Araba/Álava", value: "VI" },
      { key: "Albacete", value: "AB" },
      { key: "Alicante", value: "A" },
      { key: "Almería", value: "AL" },
      { key: "Asturies", value: "O" },
      { key: "Ávila", value: "AV" },
      { key: "Badajoz", value: "BA" },
      { key: "Les Baléares", value: "PM" },
      { key: "Barcelone", value: "B" },
      { key: "Burgos", value: "BU" },
      { key: "Cáceres", value: "CC" },
      { key: "Cádiz", value: "CA" },
      { key: "Cantabrie", value: "S" },
      { key: "Castellón", value: "CS" },
      { key: "Ceuta", value: "CE" },
      { key: "Ciudad Real", value: "CR" },
      { key: "Córdoba", value: "CO" },
      { key: "Cuenca", value: "CU" },
      { key: "Gérone", value: "GI" },
      { key: "Grenade", value: "GR" },
      { key: "Guadalajara", value: "GU" },
      { key: "Guipuscoa", value: "SS" },
      { key: "Huelva", value: "H" },
      { key: "Huesca", value: "HU" },
      { key: "Jaén", value: "J" },
      { key: "La Rioja", value: "LO" },
      { key: "Las Palmas", value: "GC" },
      { key: "León", value: "LE" },
      { key: "Lleida", value: "L" },
      { key: "Lugo", value: "LU" },
      { key: "Madrid", value: "M" },
      { key: "Málaga", value: "MA" },
      { key: "Melilla", value: "ML" },
      { key: "Murcia", value: "MU" },
      { key: "Navarre", value: "NA" },
      { key: "Ourense", value: "OR" },
      { key: "Palencia", value: "P" },
      { key: "Pontevedra", value: "PO" },
      { key: "Salamanca", value: "SA" },
      { key: "Santa Cruz de Tenerife", value: "TF" },
      { key: "Ségovie", value: "SG" },
      { key: "Séville", value: "SE" },
      { key: "Soria", value: "SO" },
      { key: "Tarragone", value: "T" },
      { key: "Teruel", value: "TE" },
      { key: "Toledo", value: "TO" },
      { key: "Valence", value: "V" },
      { key: "Valladolid", value: "VA" },
      { key: "Biscay", value: "BI" },
      { key: "Zamora", value: "ZA" },
      { key: "Saragosse", value: "Z" },
    ],
  },
  Irlande: {
    required: true,
    name: "Département",
    options: [
      { key: "Carlow", value: "CW" },
      { key: "Cavan", value: "CN" },
      { key: "Clare", value: "CE" },
      { key: "Cork", value: "CO" },
      { key: "Donegal", value: "DL" },
      { key: "Dublin", value: "D" },
      { key: "Galway", value: "G" },
      { key: "Kerry", value: "KY" },
      { key: "Kildare", value: "KE" },
      { key: "Kilkenny", value: "KK" },
      { key: "Laois", value: "LS" },
      { key: "Leitrim", value: "LM" },
      { key: "Limerick", value: "LK" },
      { key: "Longford", value: "LD" },
      { key: "Louth", value: "LH" },
      { key: "Mayo", value: "MO" },
      { key: "Meath", value: "MH" },
      { key: "Monaghan", value: "MN" },
      { key: "Offaly", value: "OY" },
      { key: "Roscommon", value: "RN" },
      { key: "Sligo", value: "SO" },
      { key: "Tipperary", value: "TA" },
      { key: "Waterford", value: "WD" },
      { key: "Westmeath", value: "WH" },
      { key: "Wexford", value: "WX" },
      { key: "Wicklow", value: "WW" },
    ],
  },
};
